USE order_db;

ALTER TABLE orders
    MODIFY COLUMN price DOUBLE NULL,
    ADD COLUMN IF NOT EXISTS shipping_address VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS shipping_city VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS shipping_state VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS shipping_zip_code VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS shipping_country VARCHAR(255) NULL;

ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS upi_id VARCHAR(255) NULL;
