server:
  port: 9002

spring:
  application:
    name: product-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:}

eureka:
  client:
    enabled: false

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}

external:
  product-api:
    base-url: ${PRODUCT_API_BASE_URL:https://dummyjson.com}

---
spring:
  config:
    activate:
      on-profile: ec2

eureka:
  client:
    enabled: false
  instance:
    hostname: localhost
